// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-6j-NInufyOnFOkf9GIEr9ZrjbON1GFE',
    appId: '1:683597520754:web:7bc58e0cf5fa8cf33ac7eb',
    messagingSenderId: '683597520754',
    projectId: 'javied-nama-iqbal',
    authDomain: 'javied-nama-iqbal.firebaseapp.com',
    databaseURL: 'https://javied-nama-iqbal-default-rtdb.firebaseio.com',
    storageBucket: 'javied-nama-iqbal.firebasestorage.app',
    measurementId: 'G-YM345K5G7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj6OCp_SzJrQBJmFESfKJcdImyAcx1UG8',
    appId: '1:683597520754:android:e8f16ff544f17efe3ac7eb',
    messagingSenderId: '683597520754',
    projectId: 'javied-nama-iqbal',
    databaseURL: 'https://javied-nama-iqbal-default-rtdb.firebaseio.com',
    storageBucket: 'javied-nama-iqbal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS41yoyCGDf2DJYtNbDG2YYcoIQj9EEZU',
    appId: '1:683597520754:ios:8541fdd863aeceaa3ac7eb',
    messagingSenderId: '683597520754',
    projectId: 'javied-nama-iqbal',
    databaseURL: 'https://javied-nama-iqbal-default-rtdb.firebaseio.com',
    storageBucket: 'javied-nama-iqbal.firebasestorage.app',
    iosBundleId: 'com.example.javadName',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS41yoyCGDf2DJYtNbDG2YYcoIQj9EEZU',
    appId: '1:683597520754:ios:8541fdd863aeceaa3ac7eb',
    messagingSenderId: '683597520754',
    projectId: 'javied-nama-iqbal',
    databaseURL: 'https://javied-nama-iqbal-default-rtdb.firebaseio.com',
    storageBucket: 'javied-nama-iqbal.firebasestorage.app',
    iosBundleId: 'com.example.javadName',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-6j-NInufyOnFOkf9GIEr9ZrjbON1GFE',
    appId: '1:683597520754:web:71d1508703b545373ac7eb',
    messagingSenderId: '683597520754',
    projectId: 'javied-nama-iqbal',
    authDomain: 'javied-nama-iqbal.firebaseapp.com',
    databaseURL: 'https://javied-nama-iqbal-default-rtdb.firebaseio.com',
    storageBucket: 'javied-nama-iqbal.firebasestorage.app',
    measurementId: 'G-PH2JZF71K8',
  );
}
